CREATE DATABASE IF NOT EXISTS muscles;

USE muscles;

CREATE TABLE IF NOT EXISTS MUSCLE_LOCATION (
    lid	    INT				PRIMARY KEY,
    mname	VARCHAR(100)	NOT NULL
);

CREATE TABLE IF NOT EXISTS MUSCLE_GROUP (
    gid	    INT				PRIMARY KEY,
    gName	VARCHAR(100)	NOT NULL
);

CREATE TABLE IF NOT EXISTS MUSCLE (
  mid       INT          PRIMARY KEY, 
  mName     VARCHAR(100)    NOT NULL,
  lid       INT,
  gid       INT,
  FOREIGN KEY (lid) REFERENCES MUSCLE_LOCATION(lid),
  FOREIGN KEY (gid) REFERENCES MUSCLE_GROUP(gid)
);

CREATE TABLE IF NOT EXISTS EXERCISE (
    eid		INT				PRIMARY KEY,
    eName	VARCHAR(100)	NOT NULL
);

CREATE TABLE IF NOT EXISTS EXERCISE_WORKS_MUSCLE (
  eid       	INT, 
  mid			INT,
  intensity		INT				DEFAULT 0,
  PRIMARY KEY (eid, mid),
  FOREIGN KEY (eid) REFERENCES EXERCISE(eid),
  FOREIGN KEY (mid) REFERENCES MUSCLE(mid),
  CHECK (intensity>=0),
  CHECK (intensity<=3)
);

SHOW TABLES;
DROP TABLE IF EXISTS MUSCLE;
ALTER TABLE MUSCLE_LOCATION RENAME COLUMN mname to lName;