CREATE DATABASE IF NOT EXISTS muscles;

USE muscles;

CREATE TABLE IF NOT EXISTS MUSCLE (
  mid       INT          PRIMARY KEY, 
  mName     VARCHAR(100)    NOT NULL 
);

CREATE TABLE IF NOT EXISTS EXERCISE (
    eid		INT				PRIMARY KEY,
    eName	VARCHAR(100)	NOT NULL
);

CREATE TABLE IF NOT EXISTS MUSCLE_LOCATION (
    mlid	INT				PRIMARY KEY,
    mlName	VARCHAR(100)	NOT NULL
);

CREATE TABLE IF NOT EXISTS MUSCLE_GROUP (
    mgid	INT				PRIMARY KEY,
    mgName	VARCHAR(100)	NOT NULL
);

CREATE TABLE IF NOT EXISTS MUSCLE_LOCATION_MUSCLE (
    mlid    INT,
    mid     INT,
    PRIMARY KEY (mlid, mid),
    FOREIGN KEY (mlid) REFERENCES MUSCLE_LOCATION(mlid),
    FOREIGN KEY (mid) REFERENCES MUSCLE(mid)
);

CREATE TABLE IF NOT EXISTS MUSCLE_GROUP_MUSCLE (
    mgid    INT,
    mid     INT,
    PRIMARY KEY (mgid, mid),
    FOREIGN KEY (mgid) REFERENCES MUSCLE_GROUP(mgid),
    FOREIGN KEY (mid) REFERENCES MUSCLE(mid)
);

SHOW TABLES;
DROP TABLE IF EXISTS MUSCLE;